FROM node:20.10.0

RUN npm install -g firebase-tools

ENTRYPOINT ["/usr/local/bin/firebase"]
#/home/firebase
#gcloud artifacts repositories create expenses-control-app-repo --repository-format=docker --location=us-west2 --description="Docker repository"